import { supabase } from '../lib/supabaseClient';
import { Devotee, Session, Notification } from '../types';

export const storageService = {
  // DEVOTEES
  getDevotees: async (): Promise<Devotee[]> => {
    const { data, error } = await supabase
      .from('devotees')
      .select('*')
      .order('name');

    if (error) throw error;

    return data.map((d: any) => ({
      id: d.id,
      name: d.name,
      spiritualName: d.spiritual_name,
      email: d.email,
      phone: d.phone,
      photo: d.photo,
      status: d.status,
      joinedAt: d.joined_at,
      hobbies: d.hobbies,
      dailyMalas: d.daily_malas
    }));
  },

  createDevotee: async (devotee: Devotee) => {
    const { error } = await supabase
      .from('devotees')
      .insert({
        // id is auto-generated by default, but if we want to force one we can. 
        // Best practice is let DB generate text UUIDs. 
        // But the frontend currently generates one. Let's use the one passed or omit.
        // Actually schema says default uuid_generate_v4().
        name: devotee.name,
        spiritual_name: devotee.spiritualName,
        email: devotee.email,
        phone: devotee.phone,
        photo: devotee.photo,
        status: devotee.status,
        joined_at: devotee.joinedAt,
        hobbies: devotee.hobbies,
        daily_malas: devotee.dailyMalas
      });
    if (error) throw error;
  },

  deleteDevotee: async (id: string) => {
    const { error } = await supabase
      .from('devotees')
      .delete()
      .eq('id', id);
    if (error) throw error;
  },

  // SESSIONS
  getSessions: async (): Promise<Session[]> => {
    const { data, error } = await supabase
      .from('sessions')
      .select('*')
      .order('date', { ascending: false });

    if (error) throw error;

    return data.map((d: any) => ({
      id: d.id,
      title: d.title,
      date: d.date,
      location: d.location,
      facilitator: d.facilitator,
      attendeeIds: d.attendee_ids || []
    }));
  },

  createSession: async (session: Session) => {
    const { error } = await supabase
      .from('sessions')
      .insert({
        title: session.title,
        date: session.date,
        location: session.location,
        facilitator: session.facilitator,
        attendee_ids: session.attendeeIds
      });
    if (error) throw error;
  },

  updateSession: async (session: Session) => {
    const { error } = await supabase
      .from('sessions')
      .update({
        title: session.title,
        date: session.date,
        location: session.location,
        facilitator: session.facilitator,
        attendee_ids: session.attendeeIds
      })
      .eq('id', session.id);
    if (error) throw error;
  },

  // NOTIFICATIONS
  getNotifications: async (): Promise<Notification[]> => {
    const { data, error } = await supabase
      .from('notifications')
      .select('*')
      .order('timestamp', { ascending: false })
      .limit(50);

    if (error) throw error;

    return data.map((d: any) => ({
      id: d.id,
      title: d.title,
      message: d.message,
      timestamp: new Date(d.timestamp),
      isRead: d.is_read,
      type: d.type
    }));
  },

  createNotification: async (notification: Notification) => {
    const { error } = await supabase
      .from('notifications')
      .insert({
        title: notification.title,
        message: notification.message,
        timestamp: notification.timestamp.toISOString(),
        is_read: notification.isRead,
        type: notification.type
      });
    if (error) throw error;
  },

  markAllNotificationsRead: async () => {
    const { error } = await supabase
      .from('notifications')
      .update({ is_read: true })
      .eq('is_read', false);
    if (error) throw error;
  },

  markAllNotificationsRead: async () => {
    const { error } = await supabase
      .from('notifications')
      .update({ is_read: true })
      .eq('is_read', false);
    if (error) throw error;
  }
};
